CLASS_NAMES = [
    "Apple___Apple_scab",
    "Apple___Black_rot",
    "Apple___Cedar_apple_rust",
    "Apple___healthy",
    "Blueberry___healthy",
    "Cherry_(including_sour)___healthy",
    "Cherry_(including_sour)___Powdery_mildew",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot",
    "Corn_(maize)___Common_rust_",
    "Corn_(maize)___healthy",
    "Corn_(maize)___Northern_Leaf_Blight",
    "Grape___Black_rot",
    "Grape___Esca_(Black_Measles)",
    "Grape___healthy",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)",
    "Orange___Haunglongbing_(Citrus_greening)",
    "Peach___Bacterial_spot",
    "Peach___healthy",
    "Pepper,_bell___Bacterial_spot",
    "Pepper,_bell___healthy",
    "Potato___Early_blight",
    "Potato___healthy",
    "Potato___Late_blight",
    "Raspberry___healthy",
    "Soybean___healthy",
    "Squash___Powdery_mildew",
    "Strawberry___healthy",
    "Strawberry___Leaf_scorch",
    "Tomato___Bacterial_spot",
    "Tomato___Early_blight",
    "Tomato___healthy",
    "Tomato___Late_blight",
    "Tomato___Leaf_Mold",
    "Tomato___Septoria_leaf_spot",
    "Tomato___Spider_mites Two-spotted_spider_mite",
    "Tomato___Target_Spot",
    "Tomato___Tomato_mosaic_virus",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus",
]

TREATMENT_MAP = {
    "Apple___Apple_scab": "Apply fungicide and remove infected leaves to limit spread.",
    "Apple___Black_rot": "Prune affected areas and improve air circulation around plants.",
    "Apple___Cedar_apple_rust": "Use resistant varieties and fungicidal sprays during early growth.",
    "Apple___healthy": "No disease detected. Continue regular watering and nutrient schedule.",
    "Blueberry___healthy": "No disease detected. Maintain optimal soil pH and watering.",
    "Cherry_(including_sour)___healthy": "No disease detected. Maintain regular care.",
    "Cherry_(including_sour)___Powdery_mildew": "Apply sulfur or neem oil. Ensure good air circulation.",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": "Use crop rotation, clean plowing, and apply appropriate fungicides.",
    "Corn_(maize)___Common_rust_": "Apply fungicides early in the season and use rust-resistant hybrids.",
    "Corn_(maize)___healthy": "No disease detected. Maintain balanced fertilization.",
    "Corn_(maize)___Northern_Leaf_Blight": "Plant resistant hybrids and apply fungicides if lesions appear early.",
    "Grape___Black_rot": "Apply fungicides at the right time and remove infected plant debris.",
    "Grape___Esca_(Black_Measles)": "Remove infected vines and apply protective pruning wound treatments.",
    "Grape___healthy": "No disease detected. Maintain proper viticulture practices.",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": "Use appropriate fungicides and maintain good canopy management.",
    "Orange___Haunglongbing_(Citrus_greening)": "Remove infected trees and control psyllid vectors with insecticides.",
    "Peach___Bacterial_spot": "Apply copper-based bactericides and avoid overhead irrigation.",
    "Peach___healthy": "No disease detected. Maintain regular orchard care.",
    "Pepper,_bell___Bacterial_spot": "Use disease-free seeds, rotate crops, and apply copper sprays.",
    "Pepper,_bell___healthy": "No disease detected. Continue standard care.",
    "Potato___Early_blight": "Apply fungicides, practice crop rotation, and maintain plant vigor.",
    "Potato___healthy": "No disease detected. Continue standard care.",
    "Potato___Late_blight": "Use resistant varieties and apply appropriate fungicides before infection spreads.",
    "Raspberry___healthy": "No disease detected. Maintain regular care.",
    "Soybean___healthy": "No disease detected. Maintain regular care.",
    "Squash___Powdery_mildew": "Apply fungicides, space plants for air circulation, and avoid overhead watering.",
    "Strawberry___healthy": "No disease detected. Maintain regular care.",
    "Strawberry___Leaf_scorch": "Remove infected leaves, improve air flow, and apply fungicides if necessary.",
    "Tomato___Bacterial_spot": "Apply copper sprays, ensure good air circulation, and avoid overhead watering.",
    "Tomato___Early_blight": "Prune lower leaves, apply fungicides, and practice crop rotation.",
    "Tomato___healthy": "No disease detected. Continue standard care.",
    "Tomato___Late_blight": "Apply fungicides immediately and remove infected plant parts.",
    "Tomato___Leaf_Mold": "Improve ventilation, avoid overhead watering, and apply fungicides.",
    "Tomato___Septoria_leaf_spot": "Remove diseased leaves, mulch around base, and apply fungicides.",
    "Tomato___Spider_mites Two-spotted_spider_mite": "Use insecticidal soap, neem oil, or introduce predatory mites.",
    "Tomato___Target_Spot": "Ensure good air circulation, avoid overhead irrigation, and use fungicides.",
    "Tomato___Tomato_mosaic_virus": "Remove infected plants, sanitize tools, and control weed hosts.",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "Control whitefly vectors using insecticides or reflective mulches.",
}

SYMPTOM_MAP = {
    "Apple___Apple_scab": [
        "Olive-green to brown leaf spots",
        "Velvety lesions on leaf surface",
        "Premature leaf drop",
    ],
    "Apple___Black_rot": [
        "Dark circular lesions on leaves",
        "Leaf edge browning",
        "Black rot spots on fruit in advanced stages",
    ],
    "Apple___Cedar_apple_rust": [
        "Bright orange-yellow spots",
        "Spore-like structures under leaves",
        "Leaf distortion in severe infection",
    ],
    "Apple___healthy": [
        "Uniform green color",
        "No visible lesions",
        "Normal leaf texture",
    ],
    "Blueberry___healthy": [
        "Healthy green leaves",
        "No spots or discoloration",
        "Normal fruit development",
    ],
    "Cherry_(including_sour)___healthy": [
        "Healthy green leaves",
        "No signs of mildew",
        "Normal leaf texture",
    ],
    "Cherry_(including_sour)___Powdery_mildew": [
        "White, powdery fungal patches on leaves",
        "Curled or distorted leaves",
        "Premature leaf drop",
    ],
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": [
        "Rectangular, gray-to-tan lesions",
        "Lesions restricted by leaf veins",
        "Blighting of entire leaves",
    ],
    "Corn_(maize)___Common_rust_": [
        "Rust-colored pustules on both leaf surfaces",
        "Yellowing of surrounding tissue",
        "Premature leaf death in severe cases",
    ],
    "Corn_(maize)___healthy": [
        "Healthy green leaves",
        "No visible lesions",
        "Normal plant growth",
    ],
    "Corn_(maize)___Northern_Leaf_Blight": [
        "Large, cigar-shaped, grayish-green lesions",
        "Lesions turning tan with age",
        "Blighted leaves starting from the bottom",
    ],
    "Grape___Black_rot": [
        "Small, light brown spots with dark borders",
        "Black, shriveled fruit mummies",
        "Black lesions on shoots",
    ],
    "Grape___Esca_(Black_Measles)": [
        "Tiger-stripe pattern on leaves",
        "Small, dark spots on berries",
        "Sudden vine wilt",
    ],
    "Grape___healthy": [
        "Healthy green leaves",
        "No visible lesions",
        "Normal vine growth",
    ],
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": [
        "Dark red to brown spots on leaves",
        "Irregularly shaped lesions",
        "Premature leaf fall",
    ],
    "Orange___Haunglongbing_(Citrus_greening)": [
        "Asymmetrical yellowing of leaves",
        "Misshapen, bitter fruit",
        "Twig dieback",
    ],
    "Peach___Bacterial_spot": [
        "Small, angular, water-soaked spots",
        "Shot-hole appearance as tissue falls out",
        "Dark lesions on fruit",
    ],
    "Peach___healthy": [
        "Healthy green leaves",
        "No visible lesions",
        "Normal plant growth",
    ],
    "Pepper,_bell___Bacterial_spot": [
        "Small, brown, water-soaked spots",
        "Yellowing and dropping of leaves",
        "Scab-like spots on fruit",
    ],
    "Pepper,_bell___healthy": [
        "Healthy green leaves",
        "No visible lesions",
        "Normal plant growth",
    ],
    "Potato___Early_blight": [
        "Dark spots with concentric rings (target board pattern)",
        "Yellowing around spots",
        "Lower leaves affected first",
    ],
    "Potato___healthy": [
        "Healthy green leaves",
        "No visible lesions",
        "Normal plant growth",
    ],
    "Potato___Late_blight": [
        "Large, dark, water-soaked lesions",
        "White fungal growth on leaf undersides",
        "Rapid browning and wilting",
    ],
    "Raspberry___healthy": [
        "Healthy green leaves",
        "No visible lesions",
        "Normal plant growth",
    ],
    "Soybean___healthy": [
        "Healthy green leaves",
        "No visible lesions",
        "Normal plant growth",
    ],
    "Squash___Powdery_mildew": [
        "White powdery spots on leaves and stems",
        "Leaves turn yellow and die",
        "Stunted plant growth",
    ],
    "Strawberry___healthy": [
        "Healthy green leaves",
        "No visible lesions",
        "Normal plant growth",
    ],
    "Strawberry___Leaf_scorch": [
        "Irregular purple to brown spots",
        "Spots lack light centers",
        "Leaves dry up and look scorched",
    ],
    "Tomato___Bacterial_spot": [
        "Small, dark, water-soaked spots on leaves",
        "Greasy-looking spots on fruit",
        "Leaf yellowing and drop",
    ],
    "Tomato___Early_blight": [
        "Dark brown spots with concentric rings",
        "Lower leaves yellow and drop",
        "Stem lesions",
    ],
    "Tomato___healthy": [
        "Healthy green leaves",
        "No visible lesions",
        "Normal plant growth",
    ],
    "Tomato___Late_blight": [
        "Large, irregularly shaped brown patches",
        "White mold on leaf undersides",
        "Rapid plant decline",
    ],
    "Tomato___Leaf_Mold": [
        "Pale green or yellow spots on upper leaf",
        "Olive-green mold on undersides",
        "Leaves curl and wither",
    ],
    "Tomato___Septoria_leaf_spot": [
        "Small, circular spots with gray centers",
        "Dark margins around spots",
        "Lower leaves turn yellow and drop",
    ],
    "Tomato___Spider_mites Two-spotted_spider_mite": [
        "Stippling or tiny yellow spots on leaves",
        "Fine webbing on leaves and stems",
        "Leaves turn bronze or yellow",
    ],
    "Tomato___Target_Spot": [
        "Small brown spots with yellow halos",
        "Concentric rings in older lesions",
        "Premature defoliation",
    ],
    "Tomato___Tomato_mosaic_virus": [
        "Mottled light and dark green leaves",
        "Stunted plant growth",
        "Fern-like leaf appearance",
    ],
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": [
        "Upward curling of leaf margins",
        "Yellowing of leaf edges",
        "Severe stunting and reduced fruit",
    ],
}
